### ISSUE TITLE
tart vm missing error on creation failure

### ISSUE THREAD

**Issue by ChristopherHX** [actions-oss/act-cli#75]
### Bug report info

```plain text
N/A
```

### Command used with act

```sh
gh act -W tart.yml -P macos-latest=tart://vm-1 --pull-if-needed
```

### Describe issue

The connection to the VM times out

### Workflow content

```yml
on: push
jobs:
  tart:
    runs-on: macos-latest
    steps:
    - run: uname -a
    - run: |
        uname -a
        sleep 5
        uname -a
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: env
```

### Relevant log output

```sh
N/A
```
